apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-lab
  labels: {app: ci-lab}
spec:
  replicas: 1
  selector:
    matchLabels: {app: ci-lab}
  template:
    metadata:
      labels: {app: ci-lab}
    spec:
      containers:
        - name: app
          image: ci-lab:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: {path: /healthz, port: 8080}
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet: {path: /healthz, port: 8080}
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ci-lab
  labels: {app: ci-lab}
spec:
  selector: {app: ci-lab}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
